// ─────────────────────────────────────────────────────────────────────────────
// Question Definitions — must questions + adaptive branching
// Every question has an impact declaration per Section 26.
// ─────────────────────────────────────────────────────────────────────────────

export type QuestionType = 'select' | 'number' | 'currency' | 'range' | 'boolean' | 'select_or_unknown';

export interface QuestionOption {
  value: string;
  label: string;
  helpText?: string;
}

export interface QuestionDef {
  id: string;
  label: string;
  helpText?: string;
  whyWeAsk: string;
  type: QuestionType;
  options?: QuestionOption[];
  placeholder?: string;
  required?: boolean;
  affects: string[];
  reason: string;
  group: string;
  allowUnknown?: boolean;
  unknownLabel?: string;
  min?: number;
  max?: number;
  step?: number;
  suffix?: string;
  prefix?: string;
}

// ── MUST QUESTIONS (≈9, always asked) ────────────────────────────────────────

export const MUST_QUESTIONS: QuestionDef[] = [
  {
    id: 'income_type',
    label: 'How do you earn your primary income?',
    helpText: 'This determines which follow-up questions we ask and how we assess your capacity.',
    whyWeAsk: 'Different income types have different stability profiles and documentation requirements.',
    type: 'select',
    options: [
      { value: 'salaried', label: 'Salaried / Fixed salary' },
      { value: 'self_employed', label: 'Self-employed / Business owner' },
      { value: 'informal', label: 'Gig work / Daily wage / Freelance' },
    ],
    required: true,
    affects: ['lenderCapacity', 'safeCapacity', 'fairRate', 'productRoute'],
    reason: 'Income type changes the FOIR applied, the retention factor, and the documentation haircut.',
    group: 'income',
  },
  {
    id: 'monthly_income',
    label: 'What is your total monthly income?',
    helpText: 'Enter your best estimate of what you take home each month, including all sources.',
    whyWeAsk: 'This is the foundation for all affordability calculations.',
    type: 'currency',
    placeholder: '50,000',
    prefix: '₹',
    required: true,
    affects: ['lenderCapacity', 'safeCapacity', 'stressTest'],
    reason: 'Income is the primary input for both lender and safe capacity calculations.',
    group: 'income',
  },
  {
    id: 'loan_purpose',
    label: 'What is the loan for?',
    whyWeAsk: 'Different purposes route to different loan products with different rates and tenures.',
    type: 'select',
    options: [
      { value: 'personal_event', label: 'Personal event (wedding, travel, etc.)' },
      { value: 'home_purchase', label: 'Home purchase' },
      { value: 'home_renovation', label: 'Home renovation' },
      { value: 'business_expansion', label: 'Business expansion / working capital' },
      { value: 'vehicle', label: 'Vehicle (two-wheeler / car)' },
      { value: 'medical', label: 'Medical expenses' },
      { value: 'education', label: 'Education' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    affects: ['productRoute', 'fairRate'],
    reason: 'Determines which loan product and rate band to use.',
    group: 'loan',
  },
  {
    id: 'requested_amount',
    label: 'How much do you want to borrow?',
    helpText: 'Enter the total amount you\'re thinking of borrowing.',
    whyWeAsk: 'We compare this against what a lender might give and what\'s safe for you.',
    type: 'currency',
    placeholder: '5,00,000',
    prefix: '₹',
    required: true,
    affects: ['decision', 'stressTest'],
    reason: 'The requested amount determines the verdict (Borrow / Borrow Less / Don\'t Borrow).',
    group: 'loan',
  },
  {
    id: 'existing_emi',
    label: 'What are your current total monthly EMI payments?',
    helpText: 'Include all loans: car, personal, home, etc. Enter 0 if you have no EMIs.',
    whyWeAsk: 'Existing debt reduces your available capacity for a new loan.',
    type: 'currency',
    placeholder: '0',
    prefix: '₹',
    allowUnknown: true,
    unknownLabel: 'I\'m not sure of the exact total',
    affects: ['lenderCapacity', 'safeCapacity', 'stressTest'],
    reason: 'Existing EMI is subtracted from available debt-service capacity.',
    group: 'debt',
  },
  {
    id: 'essential_expenses',
    label: 'What are your essential monthly expenses?',
    helpText: 'Rent, utilities, food, transport, children\'s school, insurance — everything you can\'t skip.',
    whyWeAsk: 'This tells us how much cash flow is truly available after necessities.',
    type: 'currency',
    placeholder: '25,000',
    prefix: '₹',
    allowUnknown: true,
    unknownLabel: 'I\'m not sure — give me a rough estimate',
    affects: ['safeCapacity', 'stressTest'],
    reason: 'Expenses determine disposable cash flow — the foundation of safe capacity.',
    group: 'expenses',
  },
  {
    id: 'high_cost_debt',
    label: 'Do you have any existing loans at very high interest (30%+ per year)?',
    helpText: 'This includes app-based loans, moneylender debt, credit card revolving debt, etc.',
    whyWeAsk: 'High-cost debt is the single strongest signal that new borrowing may be harmful.',
    type: 'select',
    options: [
      { value: 'none', label: 'No, I don\'t have any high-interest debt' },
      { value: 'has_debt', label: 'Yes, I have outstanding high-interest debt' },
    ],
    required: true,
    affects: ['decision', 'safeCapacity', 'fairRate', 'stressTest'],
    reason: 'High-cost debt can trigger hard stops and affects retention and rate.',
    group: 'debt',
  },
  {
    id: 'recent_bounce',
    label: 'Have you missed or bounced any loan payment in the last 3 months?',
    whyWeAsk: 'A recent bounce is a strong distress signal that affects multiple outputs.',
    type: 'select',
    options: [
      { value: 'no', label: 'No, all payments have been on time' },
      { value: 'yes', label: 'Yes, I missed or bounced a payment recently' },
    ],
    required: true,
    affects: ['decision', 'safeCapacity', 'fairRate'],
    reason: 'Bounces affect the fair rate (+20 pts), retention factor (−10 pts), and can trigger hard stops.',
    group: 'credit',
  },
  {
    id: 'dependents',
    label: 'How many people depend on your income?',
    helpText: 'Children, elderly parents, non-earning spouse — anyone you financially support.',
    whyWeAsk: 'More dependents with no other earner means less financial slack.',
    type: 'number',
    placeholder: '0',
    min: 0,
    max: 15,
    affects: ['safeCapacity'],
    reason: 'More than 2 dependents with no other earner reduces the retention factor.',
    group: 'household',
  },
];

// ── HIGH-COST DEBT FOLLOW-UP ─────────────────────────────────────────────────
export const HIGH_COST_DEBT_QUESTIONS: QuestionDef[] = [
  {
    id: 'high_cost_debt_amount',
    label: 'What is the total outstanding balance on your high-interest debt?',
    helpText: 'Your best estimate of what you currently owe across all high-interest loans.',
    whyWeAsk: 'The outstanding amount determines the severity of the burden.',
    type: 'currency',
    placeholder: '50,000',
    prefix: '₹',
    required: true,
    affects: ['decision', 'safeCapacity'],
    reason: 'Used to calculate burden as percentage of income and to estimate monthly payment if unknown.',
    group: 'debt',
  },
  {
    id: 'high_cost_debt_monthly',
    label: 'How much do you pay monthly toward this high-interest debt?',
    helpText: 'If you\'re not sure, we\'ll estimate conservatively based on the outstanding amount.',
    whyWeAsk: 'The monthly burden, not just the balance, drives the affordability math.',
    type: 'currency',
    placeholder: '5,000',
    prefix: '₹',
    allowUnknown: true,
    unknownLabel: 'I don\'t know my exact monthly payment',
    affects: ['safeCapacity', 'decision', 'stressTest'],
    reason: 'Monthly payment directly reduces disposable cash flow. If unknown, we use outstanding × 25%.',
    group: 'debt',
  },
];

// ── EXPENSE COARSE BUCKET (conditional follow-up) ────────────────────────────
export const EXPENSE_BUCKET_QUESTION: QuestionDef = {
  id: 'expense_bucket',
  label: 'Roughly, are your monthly essentials closer to:',
  helpText: 'Pick the closest option — even a rough number helps us give you a better answer.',
  whyWeAsk: 'A rough estimate is much better than a default assumption.',
  type: 'select',
  options: [
    { value: '15000', label: '₹15,000/month' },
    { value: '25000', label: '₹25,000/month' },
    { value: '40000', label: '₹40,000/month' },
    { value: '60000', label: 'More than ₹40,000/month' },
  ],
  allowUnknown: true,
  unknownLabel: 'I really can\'t estimate',
  affects: ['safeCapacity'],
  reason: 'Cheap precision gain — one follow-up materially improves safe amount accuracy.',
  group: 'expenses',
};

// ── SALARIED ADAPTIVE QUESTIONS ──────────────────────────────────────────────
export const SALARIED_QUESTIONS: QuestionDef[] = [
  {
    id: 'employment_tenure',
    label: 'How long have you been at your current job?',
    whyWeAsk: 'Longer tenure signals income stability to lenders.',
    type: 'select',
    options: [
      { value: 'lt_6mo', label: 'Less than 6 months' },
      { value: '6mo_1yr', label: '6 months to 1 year' },
      { value: '1_3yr', label: '1 to 3 years' },
      { value: '3_5yr', label: '3 to 5 years' },
      { value: 'gt_5yr', label: 'More than 5 years' },
    ],
    affects: ['fairRate', 'lenderCapacity'],
    reason: 'Employment tenure affects rate positioning and lender confidence.',
    group: 'employment',
  },
  {
    id: 'income_stability',
    label: 'Is your salary fixed or does it have a variable component?',
    whyWeAsk: 'Fixed, stable income qualifies for a 50% safe retention base, whereas variable income uses 40% base.',
    type: 'select',
    options: [
      { value: 'stable', label: 'Fixed salary — no variable component (Stable)' },
      { value: 'moderate', label: 'Mostly fixed, but has variable bonus or incentives' },
      { value: 'unstable', label: 'Significantly variable (commission / incentive heavy)' },
    ],
    allowUnknown: false,
    affects: ['safeCapacity', 'fairRate'],
    reason: 'Stability determines retention factor base (50% stable vs 40% variable) and rate adjustment.',
    group: 'employment',
  },
  {
    id: 'variable_income_share',
    label: 'What percentage of your income is variable (bonuses, commission)?',
    whyWeAsk: 'If more than 30% is variable, an additional 5 percentage point safety buffer is applied.',
    type: 'select',
    options: [
      { value: '0', label: 'None — all fixed (0%)' },
      { value: '15', label: 'About 10–20%' },
      { value: '30', label: 'About 20–30%' },
      { value: '50', label: 'More than 30%' },
    ],
    affects: ['safeCapacity'],
    reason: 'Variable income >30% reduces retention factor by 5 percentage points.',
    group: 'employment',
  },
  {
    id: 'credit_score',
    label: 'Do you know your credit score?',
    helpText: 'You can check for free on CIBIL, Experian, or through your bank app.',
    whyWeAsk: 'Credit score is the primary determinant of what rate a lender will offer.',
    type: 'select_or_unknown',
    options: [
      { value: '800', label: '750 or above (Excellent)' },
      { value: '725', label: '700–749 (Good)' },
      { value: '675', label: '650–699 (Fair)' },
      { value: '600', label: '550–649 (Below average)' },
      { value: '500', label: 'Below 550 (Poor)' },
      { value: 'thin_file', label: 'I\'ve never borrowed before (no credit history)' },
    ],
    allowUnknown: true,
    unknownLabel: 'I don\'t know my score',
    affects: ['fairRate', 'confidence'],
    reason: 'Credit score changes the fair-rate position by up to ±30 points.',
    group: 'credit',
  },
  {
    id: 'repayment_history',
    label: 'How would you describe your loan repayment history?',
    whyWeAsk: 'Clean repayment lowers your rate; a bounce significantly raises it.',
    type: 'select',
    options: [
      { value: 'clean', label: 'Always paid on time' },
      { value: 'bounce', label: 'Missed or bounced payment in the last 12 months' },
    ],
    allowUnknown: true,
    unknownLabel: 'Not sure / never had a loan',
    affects: ['fairRate', 'decision'],
    reason: 'Clean repayment: −5 rate pts. Recent bounce: +20 rate pts.',
    group: 'credit',
  },
  {
    id: 'documentation_status',
    label: 'What income documentation can you provide?',
    whyWeAsk: 'Documentation affects both the lender\'s view of your income and your rate.',
    type: 'select',
    options: [
      { value: 'full', label: 'Salary slips, bank statements, ITR — all available' },
      { value: 'partial', label: 'Some documents available but not complete' },
      { value: 'none', label: 'No formal income documentation' },
    ],
    allowUnknown: true,
    unknownLabel: 'Not sure what I have',
    affects: ['lenderCapacity', 'fairRate'],
    reason: 'Documentation determines the income haircut for lender capacity.',
    group: 'credit',
  },
];

// ── SELF-EMPLOYED ADAPTIVE QUESTIONS ─────────────────────────────────────────
export const SELF_EMPLOYED_QUESTIONS: QuestionDef[] = [
  {
    id: 'business_tenure',
    label: 'How many years have you been running this business?',
    whyWeAsk: 'Longer business tenure means we can use a more favorable income estimate.',
    type: 'number',
    placeholder: '5',
    min: 0,
    max: 50,
    suffix: 'years',
    affects: ['lenderCapacity', 'fairRate'],
    reason: 'Tenure ≥3yr → midpoint of income range used; otherwise lower bound.',
    group: 'employment',
  },
  {
    id: 'documented_income_itr',
    label: 'What is your annual ITR income (if you file)?',
    helpText: 'The income declared in your last Income Tax Return.',
    whyWeAsk: 'ITR income is your documented income — the baseline for lender calculations.',
    type: 'currency',
    placeholder: '4,00,000',
    prefix: '₹',
    suffix: '/year',
    allowUnknown: true,
    unknownLabel: 'I don\'t file ITR',
    affects: ['lenderCapacity', 'fairRate'],
    reason: 'Documented income determines how much a lender will count toward capacity.',
    group: 'income',
  },
  {
    id: 'income_range_low',
    label: 'In a bad month, what\'s the minimum you earn?',
    whyWeAsk: 'We use your income range to assess how variable your earnings are.',
    type: 'currency',
    placeholder: '30,000',
    prefix: '₹',
    affects: ['safeCapacity', 'lenderCapacity'],
    reason: 'Income range used with tenure to determine claimed total income.',
    group: 'income',
  },
  {
    id: 'income_range_high',
    label: 'In a good month, what\'s the most you earn?',
    whyWeAsk: 'The range between low and high months tells us about income stability.',
    type: 'currency',
    placeholder: '80,000',
    prefix: '₹',
    affects: ['safeCapacity', 'lenderCapacity'],
    reason: 'Range width determines income stability assessment.',
    group: 'income',
  },
  {
    id: 'income_stability_biz',
    label: 'How stable is your business income?',
    whyWeAsk: 'Stability determines how much of your disposable income can safely go to debt.',
    type: 'select',
    options: [
      { value: 'stable', label: 'Steady — consistent month to month' },
      { value: 'moderate', label: 'Seasonal but predictable' },
      { value: 'unstable', label: 'Highly variable / unpredictable' },
    ],
    allowUnknown: true,
    unknownLabel: 'Not sure',
    affects: ['safeCapacity', 'fairRate'],
    reason: 'Determines retention factor base and rate adjustment.',
    group: 'employment',
  },
  {
    id: 'collateral_available',
    label: 'Do you have any property or gold you could use as collateral?',
    whyWeAsk: 'Collateral unlocks lower rates and higher eligible amounts via secured products.',
    type: 'select',
    options: [
      { value: 'property_residential', label: 'Yes — residential property' },
      { value: 'property_commercial', label: 'Yes — commercial property (shop, office)' },
      { value: 'gold', label: 'Yes — gold' },
      { value: 'none', label: 'No collateral available' },
    ],
    affects: ['lenderCapacity', 'productRoute', 'fairRate'],
    reason: 'Collateral changes product routing, enables LTV calculation, and lowers rates.',
    group: 'loan',
  },
  {
    id: 'collateral_value',
    label: 'What is the approximate value of your collateral?',
    helpText: 'Your best estimate. A formal valuation would be needed before any lender approval.',
    whyWeAsk: 'Collateral value determines the LTV-supported loan amount.',
    type: 'currency',
    placeholder: '25,00,000',
    prefix: '₹',
    allowUnknown: true,
    unknownLabel: 'I don\'t know',
    affects: ['lenderCapacity'],
    reason: 'Collateral value × (1−20% haircut) × LTV = LTV-supported amount.',
    group: 'loan',
  },
  {
    id: 'business_debt',
    label: 'Do you have any existing business loans or debt?',
    helpText: 'Monthly EMI toward business loans (separate from personal EMI already declared).',
    whyWeAsk: 'Business debt competes for the same cash flow.',
    type: 'currency',
    placeholder: '0',
    prefix: '₹',
    suffix: '/month',
    affects: ['lenderCapacity', 'safeCapacity'],
    reason: 'Business debt EMI is subtracted from available capacity.',
    group: 'debt',
  },
  {
    id: 'co_applicant',
    label: 'Can a spouse or family member be a co-applicant?',
    helpText: 'A co-applicant\'s documented income is added to both lender and safe capacity.',
    whyWeAsk: 'Co-applicant income can significantly increase your eligible amount.',
    type: 'select',
    options: [
      { value: 'no', label: 'No co-applicant' },
      { value: 'yes', label: 'Yes — willing to add a co-applicant' },
    ],
    affects: ['lenderCapacity', 'safeCapacity'],
    reason: 'Co-applicant documented income is added to both eligible incomes.',
    group: 'household',
  },
  {
    id: 'co_applicant_income',
    label: 'What is the co-applicant\'s monthly income?',
    helpText: 'Their documented salary or recognized income.',
    whyWeAsk: 'This income is added to your eligible income for calculations.',
    type: 'currency',
    placeholder: '20,000',
    prefix: '₹',
    affects: ['lenderCapacity', 'safeCapacity'],
    reason: 'Added at full documented value to both lender and safe income.',
    group: 'household',
  },
  {
    id: 'credit_score',
    label: 'Do you know your credit score?',
    helpText: 'You can check for free on CIBIL, Experian, or through your bank app.',
    whyWeAsk: 'Credit score is the primary determinant of what rate a lender will offer.',
    type: 'select_or_unknown',
    options: [
      { value: '800', label: '750 or above (Excellent)' },
      { value: '725', label: '700–749 (Good)' },
      { value: '675', label: '650–699 (Fair)' },
      { value: '600', label: '550–649 (Below average)' },
      { value: '500', label: 'Below 550 (Poor)' },
      { value: 'thin_file', label: 'I\'ve never borrowed before (no credit history)' },
    ],
    allowUnknown: true,
    unknownLabel: 'I don\'t know my score',
    affects: ['fairRate', 'confidence'],
    reason: 'Credit score changes the fair-rate position.',
    group: 'credit',
  },
  {
    id: 'repayment_history',
    label: 'How would you describe your loan repayment history?',
    whyWeAsk: 'Clean repayment lowers your rate; a bounce significantly raises it.',
    type: 'select',
    options: [
      { value: 'clean', label: 'Always paid on time' },
      { value: 'bounce', label: 'Missed or bounced payment in the last 12 months' },
    ],
    allowUnknown: true,
    unknownLabel: 'Not sure / never had a loan',
    affects: ['fairRate', 'decision'],
    reason: 'Clean repayment: −5 rate pts. Recent bounce: +20 rate pts.',
    group: 'credit',
  },
  {
    id: 'documentation_status',
    label: 'What income documentation can you provide?',
    whyWeAsk: 'Documentation affects both the lender\'s view of your income and your rate.',
    type: 'select',
    options: [
      { value: 'full', label: 'ITR, bank statements, GST returns — all available' },
      { value: 'partial', label: 'ITR filed but below actual cash income' },
      { value: 'none', label: 'No formal income documentation' },
    ],
    allowUnknown: true,
    unknownLabel: 'Not sure what I have',
    affects: ['lenderCapacity', 'fairRate'],
    reason: 'Documentation determines the income haircut for lender capacity.',
    group: 'credit',
  },
  {
    id: 'productive_return',
    label: 'Do you expect this loan to increase your business income?',
    helpText: 'This is for your reference only — it does NOT change any calculations.',
    whyWeAsk: 'Helps frame the Negotiation Card. Does not affect any numbers.',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — I expect it to generate more income' },
      { value: 'no', label: 'No — it\'s for operations, not growth' },
    ],
    affects: ['explanationOnly'],
    reason: 'Strictly qualitative — never touches any calculation. Display framing only.',
    group: 'loan',
  },
];

// ── INFORMAL / GIG ADAPTIVE QUESTIONS ────────────────────────────────────────
export const INFORMAL_QUESTIONS: QuestionDef[] = [
  {
    id: 'income_range_low',
    label: 'In a bad month, what\'s the minimum you earn?',
    whyWeAsk: 'For irregular income, we use the lower bound to be safe.',
    type: 'currency',
    placeholder: '15,000',
    prefix: '₹',
    affects: ['safeCapacity', 'lenderCapacity'],
    reason: 'For gig/informal income, the lower bound of the range is used.',
    group: 'income',
  },
  {
    id: 'income_range_high',
    label: 'In a good month, what\'s the most you earn?',
    type: 'currency',
    placeholder: '40,000',
    prefix: '₹',
    whyWeAsk: 'The range tells us about income volatility.',
    affects: ['safeCapacity'],
    reason: 'Range width determines stability assessment.',
    group: 'income',
  },
  {
    id: 'income_stability_informal',
    label: 'How steady is your work/income?',
    whyWeAsk: 'Stability determines how much of your disposable income can safely go to debt.',
    type: 'select',
    options: [
      { value: 'stable', label: 'Get work regularly — fairly consistent' },
      { value: 'moderate', label: 'Seasonal — good and bad months' },
      { value: 'unstable', label: 'Highly irregular — no guarantee of next month' },
    ],
    affects: ['safeCapacity', 'fairRate'],
    reason: 'Determines retention factor base and rate adjustment.',
    group: 'employment',
  },
  {
    id: 'documentation_status',
    label: 'Do you have records showing your income, such as bank deposits, platform statements, invoices, or other records?',
    helpText: 'Bank account credits, delivery/ride-hailing platform earnings statements, customer receipts, or invoices.',
    whyWeAsk: 'Documented income receives full lender recognition; unrecorded cash is treated conservatively.',
    type: 'select',
    options: [
      { value: 'partial', label: 'Yes — I have records (bank deposits, app platform statements, or receipts)' },
      { value: 'none', label: 'No — all cash / no formal records' },
    ],
    allowUnknown: true,
    unknownLabel: "I don't know / Not sure",
    affects: ['lenderCapacity', 'fairRate'],
    reason: 'Determines whether documented income can be recognized by lenders.',
    group: 'credit',
  },
];

// ── CROSS-CUTTING QUESTIONS (asked after branch-specific) ────────────────────
export const CROSS_CUTTING_QUESTIONS: QuestionDef[] = [
  {
    id: 'emergency_savings',
    label: 'How many months of expenses could you cover from savings?',
    helpText: 'If you lost your income today, how long could you manage?',
    whyWeAsk: 'Savings provide a buffer — they affect your safe carrying capacity.',
    type: 'select',
    options: [
      { value: '0', label: 'Less than 1 month' },
      { value: '3', label: '1 to 6 months' },
      { value: '9', label: 'More than 6 months' },
    ],
    allowUnknown: true,
    unknownLabel: 'Not sure',
    affects: ['safeCapacity'],
    reason: '<1 month: −5 pts retention. >6 months: +5 pts retention. Unknown: no adjustment.',
    group: 'household',
  },
  {
    id: 'upcoming_large_expense',
    label: 'Do you have any large expenses coming up in the next 6 months?',
    helpText: 'Wedding, medical procedure, home repair, etc.',
    whyWeAsk: 'Known upcoming expenses should be pre-funded, not financed by new debt.',
    type: 'select',
    options: [
      { value: 'no', label: 'No major expenses expected' },
      { value: 'yes', label: 'Yes — I have a significant expense coming' },
    ],
    affects: ['safeCapacity'],
    reason: 'Upcoming expense: −5 pts retention factor.',
    group: 'household',
  },
  {
    id: 'other_earner',
    label: 'Is there another earning member in your household?',
    whyWeAsk: 'Having another earner provides a safety net if your income drops.',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — someone else also earns' },
      { value: 'no', label: 'No — I\'m the sole earner' },
    ],
    affects: ['safeCapacity'],
    reason: 'Affects the dependents adjustment — >2 dependents + no other earner = −5 pts.',
    group: 'household',
  },
];

// ── DOCUMENTED MONTHLY INCOME (adaptive follow-up for partial documentation) ──
export const DOCUMENTED_MONTHLY_INCOME_QUESTION: QuestionDef = {
  id: 'documented_monthly_income',
  label: 'How much of this monthly income can you support with records?',
  helpText: 'Examples: ITR, bank statements, invoices, salary slips, business records, or other reliable proof.',
  whyWeAsk: 'Documented income receives full lender recognition, while the undocumented portion is treated conservatively based on evidence.',
  type: 'currency',
  placeholder: '40,000',
  prefix: '₹',
  suffix: '/month',
  allowUnknown: true,
  unknownLabel: "I don't know how much is documented",
  affects: ['lenderCapacity', 'confidence'],
  reason: 'Documented portion is recognized at 100%; only the undocumented portion receives conservative treatment.',
  group: 'income',
};

